import { create } from "zustand";
import { createDynamicScopedStorage } from "@/config/storage";
import { currentAuthScope } from "@/stores/auth";
import createSelectors from "@/utils/createSelectors";
import { dispersedShuffle } from "@/utils/shuffle";

export type QueueSource = {
  type:
    | "album"
    | "playlist"
    | "artist"
    | "allSongs"
    // The whole library's track list, not an artist's ("allSongs").
    | "allTracks"
    | "likedSongs"
    | "folder"
    | "similar"
    | "mostPlayed"
    | "albumList"
    | "playlistList"
    // A track list generated by the AudioMuse-AI integration (prompt, search,
    // mood, …). Not navigable: it has no id to go back to on the server.
    | "audiomuse"
    // A ListenBrainz "created for you" playlist, resolved against the library.
    // Not navigable either: the playlist exists on ListenBrainz, not the server.
    | "listenbrainz";
  name: string;
  // Present for navigable sources (album/playlist/artist/folder)
  id?: string;
  // The source's own cover art id (artist image / album / playlist cover), used
  // by the Activity screen's group headers.
  coverArt?: string;
} | null;

export type QueueTrack = {
  id: string;
  url: string;
  title?: string;
  artist?: string;
  album?: string;
  artwork?: string;
  duration?: number;
  // Allow extra metadata without the store needing to know its shape
  // biome-ignore lint/suspicious/noExplicitAny: allow arbitrary metadata for tracks
  [key: string]: any;
};

// `queue` is always the real playback order: shuffling permutes the array
// itself rather than maintaining a parallel traversal order beside it. That is
// what every consumer renders or exports (the Queue screen, the player's
// prev/next preview, Android Auto, the server play-queue sync), so keeping a
// second order would — and did, see #137 — show tracks that never play.
interface QueueStore {
  queue: QueueTrack[];
  currentIndex: number | null;
  removePlayed: boolean;
  repeatMode: "off" | "all" | "one";
  // Shuffle mode state
  shuffle: boolean;
  // The queue's ids in their pre-shuffle order, snapshotted when shuffle is
  // turned on so turning it off can restore the source order. Null while
  // shuffle is off, where `queue` is already that order.
  originalOrderIds: string[] | null;
  // Where the current queue was played from (Spotify-style "Playing from …")
  source: QueueSource;
  setQueue: (
    tracks: QueueTrack[],
    startIndex?: number | null,
    source?: QueueSource,
  ) => void;
  clearQueue: () => void;
  setCurrentIndex: (index: number | null) => void;
  setRemovePlayed: (remove: boolean) => void;
  setRepeatMode: (mode: "off" | "all" | "one") => void;
  setShuffle: (enabled: boolean) => void;

  // Both return how many tracks were actually inserted, so callers can report
  // what happened instead of assuming the whole batch landed.
  enqueueNext: (track: QueueTrack | QueueTrack[]) => number;
  enqueueEnd: (track: QueueTrack | QueueTrack[]) => number;
  playNow: (
    tracks: QueueTrack[] | QueueTrack,
    startIndex?: number,
    source?: QueueSource,
  ) => void;

  updateTrack: (id: string, patch: Partial<QueueTrack>) => void;
  removeByIds: (ids: string[]) => void;
  removeAtIndices: (indices: number[]) => void;
  move: (from: number, to: number) => void;

  next: () => void;
  previous: () => void;

  getCurrent: () => QueueTrack | null;
  __reset: () => void;
}

// Global bound on materialized queue size. The queue is persisted to MMKV as a
// single JSON blob on every queue-reference change, and every entry carries
// full track metadata — an uncapped "play everything" (a huge playlist, all
// saved playlists at once) would balloon memory and re-serialize megabytes per
// write. Bulk loads keep a cap-sized window around the requested start track
// (what will actually play); an enqueue at the cap evicts to make room rather
// than refusing (see makeRoomFor).
export const MAX_QUEUE_TRACKS = 1000;

// Window of at most MAX_QUEUE_TRACKS containing `startIndex`. The window starts
// at the requested track so everything ahead of it survives; near the tail it
// is pulled back so the window stays full. Entries dropped behind the start are
// the ones playback would only reach via "previous"/repeat-all wrap.
function capQueueWindow(
  tracks: QueueTrack[],
  startIndex: number | null,
): { tracks: QueueTrack[]; startIndex: number | null } {
  if (tracks.length <= MAX_QUEUE_TRACKS) return { tracks, startIndex };
  const target = Math.max(0, Math.min(startIndex ?? 0, tracks.length - 1));
  const start = Math.min(target, tracks.length - MAX_QUEUE_TRACKS);
  return {
    tracks: tracks.slice(start, start + MAX_QUEUE_TRACKS),
    startIndex: startIndex == null ? null : target - start,
  };
}

// A non-empty queue keeps one slot for the track playing now, which makeRoomFor
// never evicts — so a batch bigger than that can't fit whole.
function enqueueLimit(queueLength: number): number {
  return queueLength > 0 ? MAX_QUEUE_TRACKS - 1 : MAX_QUEUE_TRACKS;
}

// Bring a queue that an enqueue pushed over the cap back under it. An explicit
// "play next"/"add to queue" must never be the thing that gets dropped (#149:
// playing a 7000-track playlist fills the window, and every enqueue after that
// silently did nothing), so the room comes out of what is already queued:
// already-played tracks first, then the far end, and only then the stretch just
// ahead of the insertion. The current track and the incoming batch are never
// touched.
function makeRoomFor(
  queue: QueueTrack[],
  currentIndex: number | null,
  insertAt: number,
  insertCount: number,
): { queue: QueueTrack[]; currentIndex: number | null } {
  let overflow = queue.length - MAX_QUEUE_TRACKS;
  if (overflow <= 0) return { queue, currentIndex };

  const next = queue.slice();
  let index = currentIndex;
  let batchStart = insertAt;

  // Played tracks are the cheapest to lose: only "previous" and a repeat-all
  // wrap ever reach them.
  const fromHead = Math.min(overflow, index ?? 0);
  if (fromHead > 0) {
    next.splice(0, fromHead);
    index = (index ?? 0) - fromHead;
    batchStart -= fromHead;
    overflow -= fromHead;
  }

  // Then the far end — hours of playback away, and already an arbitrary
  // truncation of the source list.
  const afterBatch = next.length - (batchStart + insertCount);
  const fromTail = Math.min(overflow, afterBatch);
  if (fromTail > 0) {
    next.splice(next.length - fromTail, fromTail);
    overflow -= fromTail;
  }

  // Nothing sits after the batch (an append), so take from what was queued
  // ahead of it, working back towards the current track.
  if (overflow > 0) {
    const from = Math.max((index ?? 0) + 1, batchStart - overflow);
    next.splice(from, batchStart - from);
  }

  return { queue: next, currentIndex: index };
}

// Group same-artist tracks apart rather than drawing positions independently —
// a uniform shuffle regularly stacks three tracks by one artist in a row, which
// reads as broken. Falls back to the artist name, then to nothing (each such
// track becomes its own group) when the backend gave us no artist id.
function shuffleTracks(tracks: QueueTrack[]): QueueTrack[] {
  return dispersedShuffle(tracks, (track) => {
    const id = typeof track.artistId === "string" ? track.artistId : undefined;
    if (id) return id;
    return typeof track.artist === "string" && track.artist
      ? `name:${track.artist}`
      : undefined;
  });
}

// A repeat-all wrap under shuffle starts a fresh random pass, so the loop isn't
// the same order forever. Never lead with the track that just finished.
function reshuffleForNewPass(queue: QueueTrack[]): QueueTrack[] {
  if (queue.length < 2) return queue;
  const lastId = queue[queue.length - 1].id;
  const next = shuffleTracks(queue);
  if (next[0].id === lastId) {
    const swapAt = 1 + Math.floor(Math.random() * (next.length - 1));
    [next[0], next[swapAt]] = [next[swapAt], next[0]];
  }
  return next;
}

// Keep the pre-shuffle order in step with a queue whose contents changed:
// dropped ids fall out, ids added while shuffled (enqueues) land at the end so
// turning shuffle off doesn't lose them. Only meaningful while shuffle is on.
function reconcileOriginalOrder(
  previous: string[] | null,
  queue: QueueTrack[],
): string[] {
  const present = new Set(queue.map((t) => t.id));
  const order = previous ? previous.filter((id) => present.has(id)) : [];
  const known = new Set(order);
  for (const track of queue) {
    if (!known.has(track.id)) order.push(track.id);
  }
  return order;
}

const initialQueueState = {
  queue: [] as QueueTrack[],
  currentIndex: null as number | null,
  removePlayed: false,
  repeatMode: "off" as "off" | "all" | "one",
  shuffle: false,
  originalOrderIds: null as string[] | null,
  source: null as QueueSource,
};

const useQueueBase = create<QueueStore>()((set, get) => ({
  ...initialQueueState,
  __reset: () => {
    // Pause persistence so the subsequent rehydrate() restoring the new
    // scope's data isn't preceded by an empty-state write that would
    // clobber whatever is on disk for that scope.
    hydrated = false;
    set(() => ({ ...initialQueueState }));
  },

  // Replaces the queue *without* reshuffling — its callers are the Queue
  // screen's manual reorder and the server play-queue restore, both of which
  // hand over an order that must survive verbatim. Starting playback with
  // shuffle applied is playNow's job. Omitting `source` keeps the current one,
  // so reordering the queue doesn't wipe the "Playing from …" label.
  setQueue: (tracks, startIndex = 0, source) => {
    set((state) => {
      const capped = capQueueWindow(tracks, startIndex);
      const nextTracks = [...capped.tracks];
      const nextStart = capped.startIndex;
      return {
        queue: nextTracks,
        currentIndex:
          nextTracks.length === 0
            ? null
            : nextStart != null
              ? Math.max(0, Math.min(nextStart, nextTracks.length - 1))
              : 0,
        originalOrderIds: state.shuffle
          ? reconcileOriginalOrder(state.originalOrderIds, nextTracks)
          : null,
        ...(source !== undefined ? { source } : {}),
      } as Partial<QueueStore>;
    });
  },

  clearQueue: () => {
    set(() => {
      return {
        queue: [],
        currentIndex: null,
        originalOrderIds: null,
        source: null,
      };
    });
  },

  setCurrentIndex: (index) => {
    set((state) => ({
      currentIndex:
        index == null
          ? null
          : Math.max(0, Math.min(index, state.queue.length - 1)),
    }));
  },

  setRemovePlayed: (remove) => {
    set(() => ({ removePlayed: remove }));
  },

  setRepeatMode: (mode) => {
    set(() => ({ repeatMode: mode }));
  },

  // Turning shuffle on randomises only what hasn't played yet: the head up to
  // and including the current track keeps its positions, so "previous" still
  // walks back through what was actually heard. Turning it off restores the
  // snapshotted source order and repoints at the same track.
  setShuffle: (enabled) => {
    set((state) => {
      if (enabled === state.shuffle) return state;

      if (enabled) {
        const tailStart =
          state.currentIndex != null ? state.currentIndex + 1 : 0;
        const tail = state.queue.slice(tailStart);
        return {
          shuffle: true,
          originalOrderIds: state.queue.map((t) => t.id),
          queue:
            tail.length > 1
              ? [...state.queue.slice(0, tailStart), ...shuffleTracks(tail)]
              : state.queue,
        } as Partial<QueueStore>;
      }

      const order = state.originalOrderIds;
      if (!order || state.queue.length === 0) {
        return { shuffle: false, originalOrderIds: null };
      }
      const byId = new Map(state.queue.map((t) => [t.id, t]));
      const restored: QueueTrack[] = [];
      for (const id of order) {
        const track = byId.get(id);
        if (track) {
          restored.push(track);
          byId.delete(id);
        }
      }
      // Anything the snapshot never learned about keeps its relative position.
      for (const track of state.queue) {
        if (byId.has(track.id)) restored.push(track);
      }
      const currentId =
        state.currentIndex != null
          ? state.queue[state.currentIndex]?.id
          : undefined;
      const nextIndex = currentId
        ? restored.findIndex((t) => t.id === currentId)
        : -1;
      return {
        shuffle: false,
        originalOrderIds: null,
        queue: restored,
        currentIndex: nextIndex >= 0 ? nextIndex : state.currentIndex,
      } as Partial<QueueStore>;
    });
  },

  enqueueNext: (track) => {
    let inserted = 0;
    set((state) => {
      const items = (Array.isArray(track) ? track : [track]).slice(
        0,
        enqueueLimit(state.queue.length),
      );
      if (items.length === 0) return state;
      const insertAt =
        state.currentIndex != null
          ? state.currentIndex + 1
          : state.queue.length;
      const merged = state.queue.slice();
      merged.splice(insertAt, 0, ...items);
      const fitted = makeRoomFor(
        merged,
        state.currentIndex,
        insertAt,
        items.length,
      );
      inserted = items.length;
      // "Play next" means next, shuffle or not — the inserted tracks are never
      // randomised into the rest of the queue.
      return {
        queue: fitted.queue,
        currentIndex:
          fitted.currentIndex ?? (fitted.queue.length > 0 ? 0 : null),
        originalOrderIds: state.shuffle
          ? reconcileOriginalOrder(state.originalOrderIds, fitted.queue)
          : null,
      } as Partial<QueueStore>;
    });
    return inserted;
  },

  enqueueEnd: (track) => {
    let inserted = 0;
    set((state) => {
      const items = (Array.isArray(track) ? track : [track]).slice(
        0,
        enqueueLimit(state.queue.length),
      );
      if (items.length === 0) return state;
      const insertAt = state.queue.length;
      const merged = state.queue.concat(items);
      const fitted = makeRoomFor(
        merged,
        state.currentIndex,
        insertAt,
        items.length,
      );
      inserted = items.length;
      return {
        queue: fitted.queue,
        currentIndex:
          fitted.currentIndex ?? (fitted.queue.length > 0 ? 0 : null),
        originalOrderIds: state.shuffle
          ? reconcileOriginalOrder(state.originalOrderIds, fitted.queue)
          : null,
      } as Partial<QueueStore>;
    });
    return inserted;
  },

  // The entry point for "start playing this list". With shuffle on, the track
  // the user actually picked leads and the rest of the list follows in random
  // order — so the whole context sits ahead of them, as on Spotify.
  playNow: (tracks, startIndex = 0, source = null) => {
    const capped = capQueueWindow(
      Array.isArray(tracks) ? tracks : [tracks],
      startIndex,
    );
    const items = capped.tracks;
    const cappedStart = capped.startIndex ?? 0;
    set((state) => {
      if (items.length === 0) {
        return {
          queue: [],
          currentIndex: null,
          originalOrderIds: null,
          source,
        } as Partial<QueueStore>;
      }
      const start = Math.max(0, Math.min(cappedStart, items.length - 1));
      if (!state.shuffle) {
        return {
          queue: [...items],
          currentIndex: start,
          originalOrderIds: null,
          source,
        } as Partial<QueueStore>;
      }
      const lead = items[start];
      const rest = items.filter((_, i) => i !== start);
      return {
        queue: [lead, ...shuffleTracks(rest)],
        currentIndex: 0,
        originalOrderIds: items.map((t) => t.id),
        source,
      } as Partial<QueueStore>;
    });
  },

  updateTrack: (id, patch) => {
    set((state) => {
      const idx = state.queue.findIndex((t) => t.id === id);
      if (idx === -1) return state;
      const nextQueue = state.queue.slice();
      nextQueue[idx] = {
        ...nextQueue[idx],
        ...patch,
        id: nextQueue[idx].id,
      };
      return { queue: nextQueue };
    });
  },

  removeByIds: (ids) => {
    set((state) => {
      if (ids.length === 0) return state;
      const idSet = new Set(ids);
      const originalIndex = state.currentIndex;
      const filtered = state.queue.filter((t) => !idSet.has(t.id));
      let nextIndex: number | null = originalIndex;
      if (originalIndex != null) {
        const removedBefore = state.queue
          .slice(0, originalIndex)
          .filter((t) => idSet.has(t.id)).length;
        nextIndex = originalIndex - removedBefore;
        if (nextIndex >= filtered.length) nextIndex = filtered.length - 1;
        if (filtered.length === 0) nextIndex = null;
      }
      return {
        queue: filtered,
        currentIndex: nextIndex,
        originalOrderIds: state.shuffle
          ? reconcileOriginalOrder(state.originalOrderIds, filtered)
          : null,
      } as Partial<QueueStore>;
    });
  },

  removeAtIndices: (indices) => {
    set((state) => {
      if (indices.length === 0) return state;
      const removeSet = new Set(
        indices.filter((i) => i >= 0 && i < state.queue.length),
      );
      if (removeSet.size === 0) return state;
      const filtered = state.queue.filter((_, idx) => !removeSet.has(idx));
      let nextIndex: number | null = state.currentIndex;
      if (state.currentIndex != null) {
        const currentIndex = state.currentIndex ?? 0;
        const removedBefore = [...removeSet].filter(
          (i) => i < currentIndex,
        ).length;
        nextIndex = currentIndex - removedBefore;
        if (nextIndex >= filtered.length) nextIndex = filtered.length - 1;
        if (filtered.length === 0) nextIndex = null;
      }
      return {
        queue: filtered,
        currentIndex: nextIndex,
        originalOrderIds: state.shuffle
          ? reconcileOriginalOrder(state.originalOrderIds, filtered)
          : null,
      } as Partial<QueueStore>;
    });
  },

  move: (from, to) => {
    set((state) => {
      const length = state.queue.length;
      if (from === to || from < 0 || to < 0 || from >= length || to >= length)
        return state;
      const nextQueue = state.queue.slice();
      const [item] = nextQueue.splice(from, 1);
      nextQueue.splice(to, 0, item);

      let nextIndex: number | null = state.currentIndex;
      if (state.currentIndex != null) {
        nextIndex = state.currentIndex;
        if (from === state.currentIndex) nextIndex = to;
        else if (from < state.currentIndex && to >= state.currentIndex)
          nextIndex = state.currentIndex - 1;
        else if (from > state.currentIndex && to <= state.currentIndex)
          nextIndex = state.currentIndex + 1;
      }

      return {
        queue: nextQueue,
        currentIndex: nextIndex,
      };
    });
  },

  next: () => {
    set((state) => {
      if (state.queue.length === 0) return state;
      if (state.currentIndex == null) return { currentIndex: 0 };

      // Repeat one: stay on the same track, never remove current
      if (state.repeatMode === "one") {
        return { currentIndex: state.currentIndex };
      }

      // Pop the played track and let the one behind it slide into its index.
      if (state.removePlayed) {
        const nextQueue = state.queue.slice();
        nextQueue.splice(state.currentIndex, 1);
        if (nextQueue.length === 0) {
          return {
            queue: nextQueue,
            currentIndex: null,
            originalOrderIds: null,
          };
        }
        return {
          queue: nextQueue,
          currentIndex: Math.min(state.currentIndex, nextQueue.length - 1),
          originalOrderIds: state.shuffle
            ? reconcileOriginalOrder(state.originalOrderIds, nextQueue)
            : null,
        } as Partial<QueueStore>;
      }

      const candidate = state.currentIndex + 1;
      if (candidate < state.queue.length) return { currentIndex: candidate };
      if (state.repeatMode !== "all") return { currentIndex: null };
      // Repeat-all wrap. Shuffled, the next pass gets a fresh random order.
      return state.shuffle
        ? ({
            queue: reshuffleForNewPass(state.queue),
            currentIndex: 0,
          } as Partial<QueueStore>)
        : { currentIndex: 0 };
    });
  },

  previous: () => {
    set((state) => {
      if (state.queue.length === 0) return state;
      if (state.currentIndex == null) return { currentIndex: 0 };
      if (state.repeatMode === "one") {
        return { currentIndex: state.currentIndex };
      }

      const prevIndex = state.currentIndex - 1;
      if (prevIndex >= 0) return { currentIndex: prevIndex };
      // Wrap to end only when repeating all
      if (state.repeatMode === "all") {
        return { currentIndex: state.queue.length - 1 };
      }
      return { currentIndex: null };
    });
  },
  getCurrent: () => {
    const { queue, currentIndex } = get();
    if (
      currentIndex == null ||
      currentIndex < 0 ||
      currentIndex >= queue.length
    )
      return null;
    return queue[currentIndex];
  },
}));

// Shared id→index map for the queue. Rebuilt only when `queue` reference
// changes, so callers that need to translate a track id to its position can
// do it in O(1) instead of walking the array.
let queueIndexById = new Map<string, number>();
const rebuildQueueIndex = (queue: QueueTrack[]) => {
  const m = new Map<string, number>();
  for (let i = 0; i < queue.length; i++) m.set(queue[i].id, i);
  queueIndexById = m;
};
rebuildQueueIndex(useQueueBase.getState().queue);

export const getQueueIndexById = (id: string): number =>
  queueIndexById.get(id) ?? -1;

useQueueBase.subscribe((next, prev) => {
  if (next.queue !== prev.queue) rebuildQueueIndex(next.queue);
});

// Pure view of the track `next()` would advance to, without mutating state.
// Mirrors next()'s decision order exactly (repeat-one, removePlayed, repeat-all
// wrap) so gapless/crossfade preloads always target the track the queue will
// actually land on. Returns null when playback would stop, or across a shuffled
// repeat-all wrap — that re-randomises the queue, so there is nothing stable to
// preload.
export function peekNextTrack(): QueueTrack | null {
  const s = useQueueBase.getState();
  if (s.queue.length === 0 || s.currentIndex == null) return null;
  if (s.repeatMode === "one") return s.queue[s.currentIndex] ?? null;

  if (s.removePlayed) {
    if (s.queue.length === 1) return null;
    if (s.currentIndex + 1 < s.queue.length)
      return s.queue[s.currentIndex + 1] ?? null;
    return s.queue[s.queue.length - 2] ?? null;
  }

  if (s.currentIndex + 1 < s.queue.length)
    return s.queue[s.currentIndex + 1] ?? null;
  if (s.repeatMode !== "all") return null;
  return s.shuffle ? null : (s.queue[0] ?? null);
}

/**
 * The next `count` tracks playback would reach, in order — `peekNextTrack`
 * extended over several advances, and its first element is always what
 * `peekNextTrack` returns.
 *
 * Drives the prefetch cache's pinned window (services/trackCache/prefetcher.ts).
 * Returns fewer than `count` — possibly none — wherever the queue stops being
 * predictable: a hard end without repeat-all, and a shuffled repeat-all wrap,
 * which re-randomises the queue and so has nothing stable to point at.
 */
export function peekNextTracks(count: number): QueueTrack[] {
  const s = useQueueBase.getState();
  if (count <= 0 || s.queue.length === 0 || s.currentIndex == null) return [];

  // Repeat-one never reaches another track, so the window is the current one —
  // which the prefetcher skips as already playing. Mirrors peekNextTrack rather
  // than second-guessing it.
  if (s.repeatMode === "one") {
    const current = s.queue[s.currentIndex];
    return current ? [current] : [];
  }

  const result: QueueTrack[] = [];
  const seen = new Set<string>();

  // Each advance drops the track that just played and shifts the rest up, so the
  // only way to predict more than one step is to walk a working copy.
  if (s.removePlayed) {
    const remaining = s.queue.slice();
    let index = s.currentIndex;
    while (result.length < count && remaining.length > 1) {
      remaining.splice(index, 1);
      if (index >= remaining.length) index = remaining.length - 1;
      const next = remaining[index];
      if (!next || seen.has(next.id)) break;
      seen.add(next.id);
      result.push(next);
    }
    return result;
  }

  const len = s.queue.length;
  let index = s.currentIndex;
  let scanned = 0;
  while (result.length < count && scanned < len) {
    index += 1;
    scanned += 1;
    if (index >= len) {
      if (s.repeatMode !== "all" || s.shuffle) break;
      index = 0;
    }
    const next = s.queue[index];
    if (!next || seen.has(next.id)) break;
    seen.add(next.id);
    result.push(next);
  }
  return result;
}

// Persistence is hand-rolled (instead of zustand's `persist` middleware) so
// the hot path — a track skip that only changes `currentIndex` — doesn't
// re-stringify the entire queue array on every set(). The queue and the
// pre-shuffle order are heavy fields that only re-serialize when their
// reference actually changes; the cursor blob is tiny and rewritten on any
// change.
const QUEUE_STORAGE_NAME = "queueStore";
const persistedStorage = createDynamicScopedStorage(currentAuthScope);

type CursorBlob = {
  currentIndex: number | null;
  repeatMode: "off" | "all" | "one";
  shuffle: boolean;
  source: QueueSource;
};

const keyQueue = `${QUEUE_STORAGE_NAME}:queue`;
const keyOriginalOrder = `${QUEUE_STORAGE_NAME}:originalOrder`;
const keyCursor = `${QUEUE_STORAGE_NAME}:cursor`;
// Written by versions that kept a parallel shuffle traversal beside the queue;
// dropped on the first rehydrate so it doesn't linger in MMKV forever.
const keyLegacyShuffleOrder = `${QUEUE_STORAGE_NAME}:shuffleOrder`;

const writeQueue = (queue: QueueTrack[]) => {
  try {
    persistedStorage.setItem(keyQueue, JSON.stringify(queue));
  } catch (e) {
    console.warn("[queue] persist queue failed", e);
  }
};
const writeOriginalOrder = (ids: string[] | null) => {
  try {
    persistedStorage.setItem(keyOriginalOrder, JSON.stringify(ids));
  } catch (e) {
    console.warn("[queue] persist originalOrder failed", e);
  }
};
const writeCursor = (s: CursorBlob) => {
  try {
    persistedStorage.setItem(keyCursor, JSON.stringify(s));
  } catch (e) {
    console.warn("[queue] persist cursor failed", e);
  }
};

let hydrated = false;
const hydrationListeners = new Set<() => void>();

useQueueBase.subscribe((next, prev) => {
  // Skip writes until the first rehydrate has run, otherwise the initial
  // default state would clobber whatever is on disk.
  if (!hydrated) return;
  if (next.queue !== prev.queue) writeQueue(next.queue);
  if (next.originalOrderIds !== prev.originalOrderIds)
    writeOriginalOrder(next.originalOrderIds);
  if (
    next.currentIndex !== prev.currentIndex ||
    next.repeatMode !== prev.repeatMode ||
    next.shuffle !== prev.shuffle ||
    next.source !== prev.source
  ) {
    writeCursor({
      currentIndex: next.currentIndex,
      repeatMode: next.repeatMode,
      shuffle: next.shuffle,
      source: next.source,
    });
  }
});

const readSync = (key: string): string | null =>
  // MMKV is synchronous; the StateStorage interface is just broader.
  persistedStorage.getItem(key) as string | null;

const rehydrate = (): Promise<void> => {
  try {
    const queueRaw = readSync(keyQueue);
    const orderRaw = readSync(keyOriginalOrder);
    const cursorRaw = readSync(keyCursor);
    persistedStorage.removeItem(keyLegacyShuffleOrder);
    const patch: Partial<QueueStore> = {};
    if (queueRaw) patch.queue = JSON.parse(queueRaw) as QueueTrack[];
    if (orderRaw)
      patch.originalOrderIds = JSON.parse(orderRaw) as string[] | null;
    if (cursorRaw) {
      const cursor = JSON.parse(cursorRaw) as CursorBlob;
      patch.currentIndex = cursor.currentIndex;
      patch.repeatMode = cursor.repeatMode;
      patch.shuffle = cursor.shuffle;
      patch.source = cursor.source ?? null;
    }
    // Upgrading from a build that stored the queue in source order beside a
    // separate shuffle traversal: that queue *is* the pre-shuffle order, so
    // adopt it. The shuffled traversal is lost — the queue view is truthful
    // again from here, which is the point.
    if (patch.shuffle && patch.originalOrderIds == null) {
      patch.originalOrderIds = (patch.queue ?? []).map((t) => t.id);
    }
    if (Object.keys(patch).length > 0) {
      useQueueBase.setState(patch);
    }
  } catch (e) {
    console.warn("[queue] rehydrate failed", e);
  }
  hydrated = true;
  for (const cb of hydrationListeners) cb();
  hydrationListeners.clear();
  return Promise.resolve();
};

const persist = {
  rehydrate,
  hasHydrated: () => hydrated,
  onFinishHydration: (cb: () => void) => {
    if (hydrated) {
      cb();
      return () => {};
    }
    hydrationListeners.add(cb);
    return () => hydrationListeners.delete(cb);
  },
};

const useQueue = Object.assign(createSelectors(useQueueBase), { persist });

export default useQueue;
